#ifndef INCLUDED_SDFGENERATOR_DETAIL_INTERNAL_MACRO_H
#define INCLUDED_SDFGENERATOR_DETAIL_INTERNAL_MACRO_H


#ifdef __NVCC__
	#define SDFGENERATOR_CUDA_HOST_DEVICE __host__ __device__
#else
	#define SDFGENERATOR_CUDA_HOST_DEVICE
#endif // __NVCC__


#endif // INCLUDED_SDFGENERATOR_DETAIL_INTERNAL_MACRO_H
