#ifndef INCLUDED_SDFGENERATOR_DETAIL_COMMON_MACRO_H
#define INCLUDED_SDFGENERATOR_DETAIL_COMMON_MACRO_H


#ifdef __CUDACC__
	#define SDFGENERATOR_CUDA_HOST_DEVICE __host__ __device__
#else
	#define SDFGENERATOR_CUDA_HOST_DEVICE
#endif // __CUDACC__


#endif // INCLUDED_SDFGENERATOR_DETAIL_COMMON_MACRO_H
