#ifndef INCLUDED_SDFGENERATOR_DETAIL_SWAP_SIGN_INL
#define INCLUDED_SDFGENERATOR_DETAIL_SWAP_SIGN_INL


namespace sdfGenerator
{

} // namespace sdfGenerator


#endif // INCLUDED_SDFGENERATOR_DETAIL_SWAP_SIGN_INL
